version: "3"

services:
  localstack:
    image: "localstack/localstack"
    ports:
      - "4574:4574" # lambda
    environment:
      - SERVICES=lambda
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEBUG=1
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"